version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: flexiorder_cont
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flexiorder
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
