spring:
  profiles:
    active: test
  web:
    resources:
      add-mappings: true
  main:
    allow-circular-references: true

  application:
    name: flexiorder

  datasource:
    url: jdbc:postgresql://localhost:5433/flexiorder
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    outOfOrder: true
    locations: classpath:db.migration/postgres
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  jpa:
    open-in-view: false

api:
  security:
    token:
      secret-key: ${JWT_SECRET:my-secret-key}
      expiration-time: ${JWT_TIME:2}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html