spring:
  application:
    name: flexiorder

  datasource:
    url: jdbc:mysql://localhost:3306/seu_banco_de_dados
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    sql-migration-prefix: V1__
    sql-migration-separator: _
